### ISSUE TITLE
Can´t use % in footer text

### ISSUE THREAD

**Issue by DJ-Dingo** [pibooth/pibooth#195]
If you use % in the footer text, pibooth fails

**Comment by werdeil** [comment]
Good catch, indeed I got a crash too, I'll have a look

**Comment by DJ-Dingo** [comment]
If you use %% it works. but not %

**Comment by werdeil** [comment]
The issue comes from the fact the ConfigParser interpolate the % in the value while setting the config.

I see 2 solutions:
- Inherit from RawConfigParser instead of ConfigParser
- Escape automatically the "%" into "%%" just before setting the value in the config.

@anxuae which solution do you prefer? Do you see a reason to not use RawConfigParser (interpolation used elsewhere?)

**Comment by anxuae** [comment]
Yes RawConfigParser can be used

**Comment by werdeil** [comment]
@DJ-Dingo I just pushed a fix in the master branch, it shall fix your issue too (on pibooth-lcd plugins) reopen the issue if it is not the case.
