### ISSUE TITLE
How can I change the jpg filename ?

### ISSUE THREAD

**Issue by Fabwiss** [pibooth/pibooth#383]
Hello,

Can I change the jpg filname.
**FILENAME**
This name is **YYYY-MM-DD-HH-MM-SS_pibooth.jpg** (for example :2022-08-04-16-04-49_pibooth.jpg).
I would like this filename **YYYYMMDD_HHMMSS_What-I-Want.jpg** (for example : 20220804_160449_What-I-Want.jpg).

**RAW FOLDER**
I would like folders with this name **YYYYMMDD** not **YYYY-MM-DD-HH-MM-SS**
A same folder for all originals pictures of the same day ;)

It is possible ?

Fabwiss.

**Comment by anxuae** [comment]
Hello @Fabwiss , 

For **FILENAME**, it is not possible for now. You can rename the photo using a script. We can imaging an option to rename the **What-I-Want** part in the future. But date will be never modified.

For **RAW FOLDER**, it will never be possible, because pibooth integrate a function to regenerate pictures (with new text for instance). So we need to keep the exact date
